### ISSUE TITLE
Registry tool: can we simplify `registry` configuration in containers?

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1107]
I've been trying various ways of running the `registry` tool in a container in a kubernetes cluster, and currently this seems the best way to configure the tool - I put this at the start of whatever script that I want to run:

```
# configure the registry tool to work with the service running in the cluster
registry config configurations create cluster \
	--registry.address=registry.default.svc.cluster.local:80 \
	--registry.insecure=true \
	--registry.location=global \
	--registry.project=myproject
```

It would be nice to be able to just run a container with `kubectl run shell -ti --image IMAGE -- /bin/bash` and have it open with an already-configured `registry` connection (basically automatically doing the above step). How might we do this? A container-around-a-container? A ConfigMap that pushes in `.config/registry/active_config`?

**Comment by timburks** [comment]
Running this in a dockerfile seems to work nicely:
```
# Configure the registry tool to run in a common cluster configuration.
RUN registry config configurations create cluster \
	--registry.address=registry.default.svc.cluster.local:80 \
	--registry.insecure=true \
	--registry.location=global \
	--registry.project=menagerie
```

**Comment by theganyo** [comment]
Yes, that can work, but it would make the container statically configured. The easiest way to dynamically set config in K8s would be to just set env vars: https://kubernetes.io/docs/tasks/inject-data-application/define-environment-variable-container.

**Comment by theganyo** [comment]
(Yes, we had hoped to get rid of the env vars for the CLI... but also running a CLI in a container in a K8s cluster seems a little odd...?)

**Comment by timburks** [comment]
> ...running a CLI in a container in a k8s cluster seems a little odd...

I have a "toollkit" container that has `registry`, `registry-experimental`, and a bunch of accessory tools installed (linters, generators, etc). I'd like to be able to run it in various ways as k8s jobs that either do a specific task (with a command-line passed in) or open a shell for exploring and trying the tools in the container. So in that sense, running the CLI makes sense to me. If I'm always using the CLI on the same project, I can just build my image so that it starts configured, which is handy, but maybe we want to keep/restore an environment-based override? For me this isn't urgent, but I expect it will come up for others.

**Comment by theganyo** [comment]
You should be able to use env vars like "registry.address" etc. In fact, we're still binding the old APG_ variables: https://github.com/apigee/registry/blob/main/pkg/config/config.go#L200...  but those we'd still like to remove, I think?

**Comment by theganyo** [comment]
Sorry, typo. Should be like: `export registry_project=foo`

**Comment by timburks** [comment]
That sounds great, but I haven't gotten it to work yet:
```
$ registry config list
registry.address = apiz.timbx.me:443
registry.insecure = false
registry.location = global
token-source = gcloud auth print-access-token

Your active configuration is: "home".
$ export registry_project=menagerie
$ registry get apis
Error: unsupported pattern apis
Usage:
  registry get PATTERN [flags]

Flags:
      --filter string   filter selected resources
  -h, --help            help for get
      --nested          include nested subresources in YAML output
  -o, --output string   output type (name|yaml|contents) (default "name")

Global Flags:
  -c, --config string              name of a configuration profile or path to config file
      --registry.address string    the server and port of the Registry API (eg. localhost:8080)
      --registry.insecure          if specified, client connects via http (not https)
      --registry.location string   the API Registry location
      --registry.project string    the API Registry project
      --registry.token string      the token to use for authorization to the API Registry

----
Need more help?
https://github.com/apigee/registry/wiki
```
Does it only work if there is no configuration present?

**Comment by theganyo** [comment]
I apologize... I believe we *have to* use the APG_ prefix right now because of this: https://github.com/apigee/registry/blob/main/pkg/config/config.go#L280. So, only variables like APG_REGISTRY_ADDRESS can work until we remove that prefix.

**Comment by timburks** [comment]
Great, I added #1113 for visibility. That'll be worth a revision tag. 

I assume that since this code is in `pkg/config`, every client that uses that will be affected (which would be great!).

**Comment by timburks** [comment]
@theganyo does endorsing `REGISTRY_ADDRESS` etc mean that we would stop warning about it being set when we run tests?

**Comment by theganyo** [comment]
> @theganyo does endorsing `REGISTRY_ADDRESS` etc mean that we would stop warning about it being set when we run tests?

Yes, I think so. We only emit warnings because we deprecated the APG_ env vars. If we have tests that would be broken by env vars, we should protect them appropriately.

**Comment by timburks** [comment]
The new environment variables are working great for me in a Helm chart that runs the controller:
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: controller
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: REGISTRY_ADDRESS
              value: {{ .Values.registry.host }}:{{ .Values.registry.port }}
            - name: REGISTRY_INSECURE
              value: "true"
            - name: REGISTRY_PROJECT
              value: {{ .Values.registry.project }}
            - name: REGISTRY_LOCATION
              value: global
            command:
            - registry
            - resolve
            - artifacts/manifest
          restartPolicy: OnFailure
```

But if I omit (or forget to include) `REGISTRY_LOCATION`, I get an error when the controller is run (i.e #1105):
```
Error: invalid artifact name "artifacts/manifest", must match one of: [^projects/([A-Za-z0-9-.]+)/locations/global/artifacts/([A-Za-z0-9-.]+)$ ^projects/([A-Za-z0-9-.]+)/locations/global/apis/([A-Za-z0-9-.]+)/artifacts/([A-Za-z0-9-.]+)$ ^projects/([A-Za-z0-9-.]+)/locations/global/apis/([A-Za-z0-9-.]+)/versions/([A-Za-z0-9-.]+)/artifacts/([A-Za-z0-9-.]+)$ ^projects/([A-Za-z0-9-.]+)/locations/global/apis/([A-Za-z0-9-.]+)/versions/([A-Za-z0-9-.]+)/specs/([A-Za-z0-9-.]+)(?:@([a-z0-9-]+))?/artifacts/([A-Za-z0-9-.]+)$ ^projects/([A-Za-z0-9-.]+)/locations/global/apis/([A-Za-z0-9-.]+)/deployments/([A-Za-z0-9-.]+)(?:@([a-z0-9-]+))?/artifacts/([A-Za-z0-9-.]+)$]
Usage:
registry resolve MANIFEST_ARTIFACT [flags]
...
```
Anyway, I think this is resolved now and we can follow up on the location default in #1105.
