### ISSUE TITLE
Registry tool: support `---` separator between documents in Registry YAML files

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1108]
Kubernetes YAML allows multiple documents to be concatenated in a single file, separated by a line with three dashes.

https://stackoverflow.com/questions/50788277/why-3-dashes-hyphen-in-yaml-file

This might be useful for Registry YAML. For example, we might group all the patch versions of a Kubernetes minor version into a single file:
```
apiVersion: apigeeregistry/v1
kind: Version
metadata:
  parent: apis/kubernetes
  name: v1.26.3
data:
  displayName: v1.26.3
  specs:
  - metadata:
      name: openapi
    data:
      filename: swagger.json
      mimeType: application/x.openapi+gzip;version=2.0
      sourceURI: https://raw.githubusercontent.com/kubernetes/kubernetes/v1.26.3/api/openapi-spec/swagger.json
---
apiVersion: apigeeregistry/v1
kind: Version
metadata:
  parent: apis/kubernetes
  name: v1.26.2
data:
  displayName: v1.26.2
  specs:
  - metadata:
      name: openapi
    data:
      filename: swagger.json
      mimeType: application/x.openapi+gzip;version=2.0
      sourceURI: https://raw.githubusercontent.com/kubernetes/kubernetes/v1.26./api/openapi-spec/swagger.json
---
apiVersion: apigeeregistry/v1
kind: Version
metadata:
  parent: apis/kubernetes
  name: v1.26.1
data:
  displayName: v1.26.1
  specs:
  - metadata:
      name: openapi
    data:
      filename: swagger.json
      mimeType: application/x.openapi+gzip;version=2.0
      sourceURI: https://raw.githubusercontent.com/kubernetes/kubernetes/v1.26.1/api/openapi-spec/swagger.json
---
apiVersion: apigeeregistry/v1
kind: Version
metadata:
  parent: apis/kubernetes
  name: v1.26.0
data:
  displayName: v1.26.0
  specs:
  - metadata:
      name: openapi
    data:
      filename: swagger.json
      mimeType: application/x.openapi+gzip;version=2.0
      sourceURI: https://raw.githubusercontent.com/kubernetes/kubernetes/v1.26.0/api/openapi-spec/swagger.json
```

**Comment by timburks** [comment]
We already support this, which is produced by `registry get` and read by `registry apply`:
```
apiVersion: apigeeregistry/v1
items:
  - apiVersion: apigeeregistry/v1
    kind: Version
    metadata:
      name: v1.10.0
      parent: apis/kubernetes
      labels:
        updated: "2023-03-19"
    data:
      displayName: v1.10.0
      state: production
  - apiVersion: apigeeregistry/v1
    kind: Version
    metadata:
      name: v1.10.13
      parent: apis/kubernetes
      labels:
        updated: "2023-03-19"
    data:
      displayName: v1.10.13
      state: production
  - apiVersion: apigeeregistry/v1
    kind: Version
    metadata:
      name: v1.11.0
      parent: apis/kubernetes
      labels:
        updated: "2023-03-19"
    data:
      displayName: v1.11.0
      state: production
```
