### ISSUE TITLE
Registry tool: default configuration for hosted instances

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1176]
Looking at possible demos and hosted user flows, it seems useful to have a default configuration that doesn't require users to explicitly set `insecure`, `location`, and even `address` and `project`.

One way to do this would be to have `registry config configurations create` recognize certain names (like `gcloud`) and automatically create a configuration that gets values from a user's current `gcloud` configuration
```
registry config configurations create gcloud
```

Another possibility that is almost as simple for users would be to add a `--gcloud` flag to the above command that  creates a new configuration and populates it from the current `gcloud` configuration.
```
registry config configurations create hosted --gcloud
```
In either case, it could fail if no such configuration is present.

Neither of the above approaches would track changes to the `gcloud` configurations. We might do that by defining a special "magic" configuration named `gcloud` that always pulls from the current `gcloud` configuration. This could be enabled with the following:
```
registry config configurations activate gcloud
```

We could also make `gcloud` be the default configuration (when no configuration files are present).

Note that this should always be overridable, because users might use a registry in one Google Cloud project with resources in other projects.

**Comment by timburks** [comment]
Here's a proposal:
1. When no configuration is present, derive an implicit configuration from the current `gcloud` configuration. This makes the common case very easy. If `cloud` is not present or is unconfigured, we retain our current behavior for unconfigured registry tools.
2. Add a `--gcloud` flag to `registry config configurations create` which captures the current `gcloud` configuration into a `registry` configuration that does not track changes to the `gcloud` configuration. This makes the more advanced case of working with multiple projects possible.

**Comment by timburks** [comment]
Even simpler, could we make the setup-registry action just use the following values as defaults?

```
    - uses: apigee/registry/.github/actions/setup-registry@main
      with:
        name: cloud
        project: ${{ env.GCP_PROJECT }} # set by setup-gcloud action
        address: apigeeregistry.googleapis.com:443
        insecure: false
        token-source: gcloud auth print-access-token
```
(from [here](https://github.com/apigee-apihub-demo/petstore/blob/afda9ac2b860111e43905bee6cedb32147c8476d/.github/workflows/apply.yaml#LL47C2-L53C53))
