### ISSUE TITLE
Registry tool: should `registry apply` merge fields?

### ISSUE THREAD

**Issue by timburks** [apigee/registry#1221]
A user suggested that it would be helpful if `registry apply` could merge values in artifacts. For example, after the following two files were applied, there would be a single artifact with both `team` and `email` fields set. Currently each `apply` fully replaces an existing artifact.

```
apiVersion: apigeeregistry/v1
kind: FieldSet
metadata:
  parent: apis/sample
  name: support
data:
  definitionName: projects/PROJECTID/locations/global/artifacts/support
  values:
    team: "Team"
```

```
apiVersion: apigeeregistry/v1
kind: FieldSet
metadata:
  parent: apis/sample
  name: support
data:
  definitionName: projects/PROJECTID/locations/global/artifacts/support
  values:
    email: "apiteam@acme.com"
 ```
