### ISSUE TITLE
Applying a Spec resource from standard input doesn't upload the spec

### ISSUE THREAD

**Issue by jonblack** [apigee/registry#1227]
Given the following Spec resource in the file resource.yaml:

```yaml
apiVersion: apigeeregistry/v1
items:
  - apiVersion: apigeeregistry/v1
    kind: Spec
    metadata:
      name: reg-supplier
      parent: apis/reg-supplier/versions/1.0.0
    data:
      filename: regsupplier-app/target/openapi.json
```

It's successfully published to the registry when running:

```
registry apply -f resource.yaml
```

When applying the resource from standard input the specification is created with the filename in the resource; however, the specification content is not published.

```bash
RESOURCE=$(cat resource.yaml)
echo "$RESOURCE" | registry apply -f -
```

GetApiSpecContents when using gRPC UI returns the following:

```json
{
  "content_type": "",
  "data": "",
  "extensions": []
}
```

I would expect the specification content to be uploaded when applying from standard input.
