### ISSUE TITLE
Registry tool: Representation for dependencies in a registry.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#128]
As API registries grow, we expect that users will want them to include generated artifacts that are computed automatically in response to additions and changes to registry entries. For example, a linter might be run on every new spec revision, and a summarization of linting results for a collection of APIs might be updated after each new linting run.

This could be supported with custom applications that watch pubsub events and trigger actions. However, since these "dispatchers" might share a lot of common code, it could be useful to have a generic dispatcher that could be configured with a representation of artifact dependencies. Without suggesting how a dispatcher might be implemented, here is a sketch of a possible dependency description:

```
# API Registry Manifest
#
# This file describes the desired state of the API Registry for a project.
# It is attached (serialized) to the project using the "manifest" artifact id.
# e.g. projects/myproject/artifacts/manifest with MIME Type
#    "application/octet-stream;type=google.cloud.apihub.applications.v1alpha1.Manifest"
#

# The artifacts field lists artifacts that we want to exist in the API Registry.
# Each artifact has dependencies and a worker action that generates it.
artifacts:

# A project-level summary of registry contents.
# No owning resource is specified,
# so this defaults to belong to the project that owns this manifest.
# In the declarations below, "$0" is the matching resource, the owner of the artifact.
- artifact: summary
  dependencies:
  - resource: apis/-
  - resource: apis/-/versions/-
  - resource: apis/-/versions/-/specs/-
  action: "compute summary $0"

# Spectral linter results for OpenAPI specs.
# The filter field limits this to specs with OpenAPI mime types.
- artifact: lint-spectral
  resource: apis/-/versions/-/specs/-
  filter: "mime_type.contains('openapi')"
  dependencies:
  - resource: $0
  action: "compute lint $0 --linter spectral"

# Spectral lintstats summaries for OpenAPI specs.
# "lintstats-" artifacts depend on and summarize "lint-" artifacts.
- artifact: lintstats-spectral
  resource: apis/-/versions/-/specs/-
  filter: "mime_type.contains('openapi')"
  dependencies:
  - artifact: lint-spectral
    resource: $0
  action: "compute lintstats $0 --linter spectral"

# Project-level Spectral lintstats.
# These depend on "lintstats-spectral" artifacts of individual specs.
- artifact: lintstats-spectral
  dependencies:
  - artifact: lintstats-spectral
    resource: apis/-/versions/-/specs/-
    filter: "mime_type.contains('openapi')"
  action: "compute lintstats $0 --linter spectral"

# AIP linter results for Protobuf specs.
# These are essentially just like the Spectral linter results (above).
- artifact: lint-aip
  resource: apis/-/versions/-/specs/-
  filter: "mime_type.contains('protobuf')"
  dependencies:
  - resource: $0
  action: "compute lint $0 --linter aip"

# Vocabulary of an API spec.
- artifact: vocabulary
  resource: apis/-/versions/-/specs/-
  dependencies:
  - resource: $0
  action: "compute vocabulary $0"

# Vocabulary of APIs with a particular owner.
- artifact: vocabulary-google
  dependencies:
  - resource: apis/-/versions/-/specs/-
    filter: "owner == 'google'"
  action: "compute vocabulary union $0 --filter \"owner == 'google'\""

- artifact: vocabulary-google-common
  dependencies:
  - resource: apis/-/versions/-/specs/-
    filter: "owner == 'google'"
  action: "compute vocabulary intersection $0 --filter \"owner == 'google'\""

# The labellings field lists resources with automatically-computed labels.
labellings:

# Compute labels indicating the owner, spec formats, and
# the number of specs and versions of the API
- resource: apis/-
  dependencies:
  - resource: $0/versions/-
  - resource: $0/versions/-/specs/-
  action: "compute labels $0"

# Workers can be specified alongside actions.
# If a worker is unspecified, the default worker should be used and must be in the list below.
workers:
  # The default worker runs the registry tool.
  - name: default
    host: myworker.mydomain.com
    path: /registry
```

Comments?
