### ISSUE TITLE
Registry Controller: Support for External tasks (interaction with non-db entities)

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#260]
Currently, the controller supports tasks which are directly related to the entities stored in the database. For example, controller can currently calculate lint artifacts which are directly stored in the database as a blob. 

However, there can be some external tasks which compute artifacts which are not necessarily stored in the database directly. 
For example, one of the tasks in computing search index. For such tasks, the artifact produced in not directly stored in the registry database schema. 

This issue is to track support for such tasks. For example, we can create a place holder artifact in the registry at project level to track the action of computing search-index. This placeholder artifact will be updated like `touch` operation after a successful execution of the underlying action.

**Comment by shrutiparabgoogle** [comment]
In this scenario, it feels important to capture the details like:
* There is no artifact stored by the external action in the registry.
* Instead we will track the action by creating a placeholder artifact which will only have timestamp information
* So the manifest should represent these details. Thinking of the following change to capture in a flag:
```
name: "test-manifest"
generated_resources:
- pattern: artifacts/specs-search-index
   placeholder: true
   dependencies:
   - pattern: apis/-/versions/-/specs/-
   action: "compute search-index $0.pattern"
```

This will help the users to understand that the action is not storing any artifact in the registry, instead the action is represented with a placeholder artifact.

From the implementation POV, the controller can update the timestamp of (`touch`) the placeholder artifact after successful execution of the action (and avoid doing the `touch` operation for every single action executed).
