### ISSUE TITLE
Registry Controller: Add validation for incorrect grouping and actions

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#292]
While testing the error paths in the controller framework, one invalid path was identified which did not produce any errors but generated incorrect actions. Example:

```
- pattern: apis/-/artifacts/lintstats-gnostic
  dependencies:
  - pattern: $resource.api/versions/-/specs/-/artifacts/lint-gnostic
  action: "compute lintstats $0 --linter gnostic"
```

In the above example, the grouping is defined at the version level in the dependency pattern `$resource.version`. Hence, the dependencyMap will be formed as follows:

**key**: `projects/demo/locations/global/apis/petstore` 
**resources**: [`projects/demo/locations/global/apis/petstore/versions/1.0.0/specs/openapi.yaml/artifacts/lint-gnostic`, 
`projects/demo/locations/global/apis/petstore/versions/1.0.1/specs/openapi.yaml/artifacts/lint-gnostic`] 
**latestTimestamp**: `some time`

**key**: `projects/demo/locations/global/apis/wordnik.com` 
**resources**: [`projects/demo/locations/global/apis/wordnik.com/versions/1.0/specs/openapi.yaml/artifacts/lint-gnostic`, 
`projects/demo/locations/global/apis/wordnik.com/versions/2.0/specs/openapi.yaml/artifacts/lint-gnostic`] 
**latestTimestamp**: `some time`

The action is mentioned as follows: 
`compute lintstats $0 --linter gnostic`

The controller decides whether to execute an action, by comparing each group in the dependencyMap with it's corresponding target resource, example for first group as follows:

Compare timestamp of group `projects/demo/locations/global/apis/petstore` with timestamp of `projects/demo/locations/global/apis/petstore/artifacts/lintstats-gnostic`

Now, while computing the action, there are two options for the `$0` reference. Since, $0 refers to the resource itself, it can pick either of the two resources present in the group: [`projects/demo/locations/global/apis/petstore/versions/1.0.0/specs/openapi.yaml/artifacts/lint-gnostic`, 
projects/demo/locations/global/apis/petstore/versions/1.0.1/specs/openapi.yaml/artifacts/lint-gnostic`]

This will lead to the controller generating non-deterministic actions and also incorrect actions sometimes. The user should be notified in this case that their manifest pattern in incorrect. 

The correct action here should be `compute lintstats $0.api/versions/-/specs/-/artifacts/lint-gnostic --linter gnostic`. This will make sure that all the specs in a particular API are passed as args to the action. 

Add another option for reference like `$0.pattern` which will substitute the pattern which is defined in the manifest.

**Action items:**
**1. Define what patterns of grouping and actions are considered to be valid.**
**2. Add validation checks and throw an error if the manifest definition deviates from the allowed patterns.**

**Comment by shrutiparabgoogle** [comment]
cc @timburks

**Comment by shrutiparabgoogle** [comment]
Valid combinations of dependency group and actions:

1) All the dependencies should be grouped at the same level:
   **Valid pattern:**
   ```yaml
   - pattern: apis/-/artifacts/score
     dependencies:
     - pattern: $resource.api/versions/-/complexity
     - pattern: $resource.api/versions/-/vocabulary
   ```
   **Invalid pattern:**

   ```yaml
    - pattern: apis/-/artifacts/score
      dependencies:
      - pattern: $resource.api/versions/-/artifacts/complexity
      - pattern: $resource.versions/artifacts/vocabulary
   ```

   The grouping should either be at the api level or version level.

2) The references in the action
     - can contain only the same level entity as the group or 
     - include the dependency pattern as is
     - `$0` reference is ambiguous and creates confusion, hence the current uses of `$0` can be replaced with `$0.pattern`.
    Example: If the grouping is happening at the `api` level, then the references in the action cannot contain `$0.version` or `$0.spec`. It can contain only `$0.api/...` or `$0.pattern` (for the original dependency).

**Valid pattern:**
   ```yaml
  generated_resources:
  - pattern: apis/-/versions/-/specs/-/artifacts/lint-gnostic
     dependencies:
     - pattern: $resource.spec
     action: "compute lint $0.spec --linter gnostic" #$0.pattern will also produce the same result
   - pattern: apis/-/versions/-/specs/-/artifacts/lintstats-gnostic
     dependencies:
     - pattern: $resource.spec/artifacts/lint-gnostic
     action: "compute lintstats $0.pattern --linter gnostic"
   - pattern: apis/-/artifacts/search-index
     dependencies:
     - pattern: apis/-/versions/-/specs/-
     action: "compute search-index $0.pattern"
   - pattern: apis/-/artifacts/summary
     dependencies:
     - pattern: $resource.api/versions/-/specs/-
     action: "compute summary $0.api/versions/-/specs/-" # $0.pattern should also work
  ``` 
**Invalid pattern:**
```yaml
  generated_resources:
   - pattern: apis/-/artifacts/lintstats-gnostic
      dependencies:
      - pattern: $resource.api/versions/-/specs/-/artifacts/lint-gnostic
      # The correct action can be "compute lintstats $0.pattern --linter gnostic" ($0.pattern will be substituted with apis/petstore/versions/-/specs/-/artifacts/lint-gnostic)
      action: "compute lintstats $0.spec --linter gnostic" 
   # The above action is incorrect since the grouping is at the api level and the command is at the spec level, there is only one action computed for each group currently. 
   # ($0.spec will be substituted as apis.petstore/versions/1.0.0/specs/openapi.yaml or any other spec in that api group)
  - pattern: apis/-/versions/-/specs/-/artifacts/summary
     dependencies:
     - pattern: $resource.spec
     action: "compute summary $0.version/-/specs/-" 
     # The above action is incorrect because the controller will generated duplicate actions for two difference specs in the same version. 
    # Hence, the reference should be neither higher nor lower in hierarchy as compared to the grouping mentioned.
  ```
