### ISSUE TITLE
Add `mime_type` check in conformance command

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#427]
An example style guide definition is as follows:

```yaml
id: openapitest
mime_types:
  - application/x.protobuf+zip
guidelines:
  - id: refproperties
    display_name: Govern Ref Properties
    description: This guideline governs properties for ref fields on specs.
    rules:
      - id: norefsiblings
        description: An object exposing a $ref property cannot be further extended with additional properties.
        linter: sample
        linter_rulename: no-$ref-siblings
        severity: ERROR
    status: ACTIVE
linters:
  - name: sample
    uri: https://sample/url
```

The conformance command should check for `mime_type` of the spec, pick the style guides which have the matching `mime_types` and compute conformance against those.

Once the conformance command is integrated with the controller, the user journey will be as follows:

- The platform admin team will upload a style guide definition.
- The controller will be configured to run the compute conformance command for every new/updated spec.
- Style guides will offer a way for platform admins to enforce standards across the project.
- Any updates or new style guide definitions will be automatically picked up by the conformance command to compute the artifacts, no need to update the manifest definition for any updates to styleguides.
