### ISSUE TITLE
Registry tool: Kubernetes-style resource import

### ISSUE THREAD

**Issue by timburks** [apigee/registry#450]
We've prototyped a variety of ways to use the Registry API to add information to the registry, including custom importers for the Google API Discovery Format, the public Protocol Buffer descriptions of Google APIs, and the apis.guru OpenAPI Directory. But these are all very specialized and seem unlikely to be useful by teams in practice.

We could leave it to users to write their own importers, but we've noticed that other projects have been following a pattern that we first saw in Kubernetes - describing [objects](https://kubernetes.io/docs/concepts/overview/working-with-objects/kubernetes-objects/) (resources) with YAML that is in a standardized wrapper that includes API version and a type identifier, along with other metadata, to identify the type of object being described. This allows users to create or modify objects using a single command: [`kubectl apply`](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#apply).

Closely following the Kubernetes pattern, a YAML file for a sample API might look like this:
```
apiVersion: registry/v1
kind: API
metadata:
  name: registry
data:
  displayName: "Apigee Registry API"
  description: "The Registry API allows teams to track and manage machine-readable descriptions of APIs."
  availability: PREVIEW
  recommendedVersion: v1
  recommendedDeployment: 
  versions:
  - metadata:
      name: v1
    data:
      displayName: "v1"
      description: "New in 2022"
      state: STAGING
      specs:
      - metadata:
          name: "protos"
        data:
          filename:
          description:
          sourceURI:
  deployments:
  - metadata:
      name: prod
    data:
      displayName: Production
      description:
      specRevision:
      endpointURI: https://apigeeregistry.googleapis.com
      externalChannelURI:
      intendedAudience:
      accessGuidance:
```

Analogously to `kubectl`, the `registry` tool could have an `apply` subcommand and if we followed the `kubectl` pattern for resource access,  `registry get <resourcename> -o yaml` would return a YAML representation of objects in a form consistent with the example above.
