### ISSUE TITLE
Registry scores: Validation check

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#515]
Create a validation function to check for valid `ScoreDefinition`s and `ScoreCardDefinition`s before uploading to the registry.

**Comment by shrutiparabgoogle** [comment]
Validation logic for `ScoreDefinition`:

Example:
```
id: "test-score-definition"
kind: "ScoreDefinition"
target_resource:
  pattern: "apis/-/versions/-/specs/-"
score_formula:
  pattern:
    pattern: "$resource.spec/artifacts/conformance-report"
  score_expression: "size(conformance.GuidelineReportGroups[2].RuleReportGroups[1])"
integer: 
  min_value: 0
  max_value: 100
  thresholds:
  - severity: ALERT
    range:
      min: 60
      max: 100
  - severity: OK
    range:
      min: 0
      max: 59
```

**Validation checks:**
1. `target_resource.pattern` should always be a valid resource/collection pattern.
2. `score_formula.pattern.pattern` should always start with a `$resource.(api|version|spec|artifact)` reference.
     - the reference entity `(api|version|spec|artifact)` should be valid w.r.t `target_resource.pattern`.
     - `score_formula.pattern.pattern` cannot end with `-`. (This condition will be applied until we support aggregate operations in CEL expressions https://github.com/apigee/registry/issues/520)
3. Validate `thresholds`:
    - All of the threshold values should be under the `min`, `max` range of the score.
    - There cannot be any overlap between the range of different `severity` levels.
    - Each `severity` level can be configured only once.

These conditions can be revisited if we decide to support more advanced patterns.
