### ISSUE TITLE
Registry tool: `registry apply` should allow tags to be set in imported YAML.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#602]
Currently imported YAML files can refer to tagged specs in deployment records [here](https://github.com/apigee/registry/blob/67f42553312cf971a5314a24929c861d893603bb/cmd/registry/cmd/apply/testdata/sample/apis/registry.yaml#L48) but there is no way to associate tags with specs as they are being imported in YAML.

One way to provide this would be to include tags to be applied as part of the spec resource in the YAML. We might do this with a `revision_tags` field on the spec, as in the following example of a spec section of YAML:
```
specs:
  - metadata:
      name: openapi.yaml
      labels:
        openapi-verified: "true"
      annotations:
        linters: spectral,gnostic
    data:
      filename: openapi.yaml
      description: OpenAPI description of the Registry API
      mimeType: application/x.openapi+gzip;version=3
      sourceURI: https://raw.githubusercontent.com/apigee/registry/main/openapi.yaml
      revisionTags:
        - latest
```
With this, the `latest` tag would (need to) be applied to the spec revision after it is created for the import. It would replace any existing `latest` tag associated with the spec.
