### ISSUE TITLE
Registry controller: Parallel execution of actions leads to lost updates

### ISSUE THREAD

**Issue by shrutiparabgoogle** [apigee/registry#641]
This issue was recently discovered in the way the controller executes actions.

An example of the dependency relationship between resources is as follows:
```
- pattern: apis/-/versions/-/specs/-/artifacts/conformance-receipt
   receipt: true
   dependencies:
     - pattern: $resource.spec
     - pattern: artifacts/apihub-styleguide
   action: registry compute conformance $resource.spec
- pattern: apis/-/versions/-/specs/-/artifacts/score-receipt
   dependencies:
      - pattern: $resource.spec
      - pattern: artifacts/conformance-apihub-styleguide
   action: registry compute score $resource.spec
```

In the above definition, the controller reads these dependencies, fetches all the resources in the form of a snapshot of the state of the registry. 

Consider the case where:
- the `conformance-report` was computed for the first time in the last run.
- there has been a spec update since the last run.

In the current run:
- The controller will notice that there is a spec update and hence it will generate the action for compute conformance report.
- Since the score artifact doesn't exist yet, it will also generate an action to compute the score.
- Now, both the above actions will be submitted to a task queue to be run in parallel.
- Depending on when the task queue delegates this action to the workers for execution, there is a scenario where:
   * the score command fetches the artifact to be processed for score computation. After this fetch happens, the conformance command gets executed in parallel and updates the conformance report.
   * Then the score gets computed using the old copy and uploaded to the registry. 
   * The next time the controller runs and compares the timestamps of the conformance report and the score, it will see that the score was generated after the conformance report and hence the controller will conclude that the score is already up-to-date.
- In this whole scenario we lost an update to the conformance report and the score will remain outdated unless there is one more update to the conformance report in the future.

**Solution:**
- Modify the [timestamp condition](https://github.com/apigee/registry/blob/main/cmd/registry/controller/controller.go#L351) used by the controller to determine if an update is needed or not.
- The current condition simply checks if the resource was generated after it's dependencies. This condition can be modified to include a threshold:
```
resources should be at least N seconds newer than their dependencies, where N is the maximum time to compute the resource.
```
