### ISSUE TITLE
Registry tool: support `registry apply` YAML import of deployments, versions, and specs

### ISSUE THREAD

**Issue by timburks** [apigee/registry#771]
Currently all resources imported with `registry apply` have a project/location as parent. This issue is about support for creating other resource types with `registry apply`.

As an example, here is a description of the Google Books sample API:
```
# books.yaml
apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: books
data:
  displayName: Google Books API
  description: Books API
  versions:
    - metadata:
        name: v1
      data:
        specs:
          - metadata:
              name: openapi.yaml
            data:
              filename: openapi.yaml
              mimeType: application/x.openapi+gzip;version=3
              sourceURI: https://raw.githubusercontent.com/APIs-guru/openapi-directory/754babf60fe7fae589c43afea8ff31c44cfb48e9/APIs/googleapis.com/books/
v1/openapi.yaml
```

This can be imported with `registry apply`:
```
registry apply -f books.yaml
```

It contains version and spec subresources. We might break it into parts as follows:
```
# books.yaml
apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: books
data:
  displayName: Google Books API
  description: Books API
```

```
# books-v1.yaml
apiVersion: apigeeregistry/v1
kind: Version
metadata:
    name: v1
    parent: apis/books
```

```
# books-v1-openapi.yaml
apiVersion: apigeeregistry/v1
kind: Spec
metadata:
  name: openapi.yaml
  parent: apis/books/versions/v1
data:
  filename: openapi.yaml
  mimeType: application/x.openapi+gzip;version=3
  sourceURI: https://raw.githubusercontent.com/APIs-guru/openapi-directory/754babf60fe7fae589c43afea8ff31c44cfb48e9/APIs/googleapis.com/books/v1/openapi.yaml
```

Note that the subresources use the `metadata.parent` field to specify the parent of the resource. To make YAML files portable across projects, `metadata.parent` fields do not include the containing project and location.  Artifacts attached to non-project resources could also be represented similarly. This allows these YAML files to be applied with `registry apply` and only the containing project and location, which can be omitted if it is specified in the registry tool configuration.

```
# create the API
registry apply -f books.yaml
# create the version
registry apply -f books-v1.yaml
# create the spec
registry apply -f books-v1-openapi.yaml
```

We could also keep the version description in the API description.
```
# books.yaml
apiVersion: apigeeregistry/v1
kind: API
metadata:
  name: books
data:
  displayName: Google Books API
  description: Books API
  versions:
    - metadata:
        name: v1
```
