### ISSUE TITLE
Registry tool: `registry apply` does not support YAML project descriptions.

### ISSUE THREAD

**Issue by timburks** [apigee/registry#907]
For open-source installations, I think I should be able to use `registry apply` and the following YAML to set project properties:
```
apiVersion: apigeeregistry/v1
kind: Project
metadata:
  name: openapi
data: 
  displayName: OpenAPI Directory
  description: APIs from the APIs.guru OpenAPI Directory
```

Following that, I should get matching output from `registry get` and `registry export` should write it into an `info.yaml` at the project level. Currently the `apply` and `export` parts of this are not implemented.
